config/routes.rb
MayBall::Application.routes.draw do
  get 'metrics/cashflow'

  get 'metrics/payments'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root 'users#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'home', to: 'users#home'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket_type
  has_many :charges, dependent: :destroy

  validates :user, :ticket_type, :donation, :name, :second_name, presence: true
  validates :donation, numericality: { greater_than_or_equal_to: 0 }
  # validate :ticket_type_must_be_available
  validate :ticket_type_must_not_be_sold_out, on: :create
  validate :first_guest_birthday_eighteen
  validate :second_guest_birthday_eighteen

  def first_guest_birthday_eighteen
    if self.first_guest_date_of_birth > Date.new(2015,6,17) - 18.years
      errors.add(:first_guest_date_of_birth, 'Guests must be at least 18 years old on the day of the ball.')
    end
  end

  def second_guest_birthday_eighteen
    if self.second_guest_date_of_birth > Date.new(2015,6,17) - 18.years
      errors.add(:second_guest_date_of_birth, 'Guests must be at least 18 years old on the day of the ball.')
    end
  end

  def ticket_type_must_not_be_sold_out
    if self.ticket_type.sold_out
      errors.add(:ticket_type, 'That particular ticket type is now sold out. Please choose another.')
    end
  end

  # def ticket_type_must_be_available
  #   unless self.user.available_ticket_groups.pluck(:id).include? ticket_type_id
  #     errors.add(:ticket_type, "The ticket type you have chosen is not available.")
  #   end
  # end

  def payment_deadline
    return self.charges.pluck(:created_at).last + 60*60*24*7
  end

  def move_from_waiting_list_to_reserved!
    if self.waiting_list?
      self.build_charges!
      self.status = :reserved
      if self.save!({validate: false})
        UserMailer.waiting_list_approved(self.user, self).deliver_later
      else
        return self.errors
      end
    end
  end

  def build_charges!
    self.charges.build([{amount: self.ticket_type.price, description: self.ticket_type.name},
                        {amount: self.donation, description: 'Ticket donation'}])
  end

  after_initialize :assign_default_values

  enum status: [
    :reserved,
    :waiting_list,
    :not_allocated,
    :confirmed,
    :printed,
    :admitted
  ]

  private
    def assign_default_values
      self.status = :reserved if self.status.nil?
      self.donation = 0 if self.donation.nil?
    end
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  has_many :tickets

  after_initialize :assign_default_values
  validates :name, :price, :max_number, :number_allocated, :size, presence: true

  def self.for_sale
    TicketType.where(:for_sale => true)
  end

  def sold_out
    self.tickets.where(status: Ticket.statuses[:reserved]).count >= self.max_number
  end

  def revenue
    self.price * self.tickets.count
  end

  def self.total_revenue
    self.all.map { |x| x.revenue}.reduce(:+)
  end

  def short_name
    name = self.name
    c = "champagne"
    d = "dining"
    s = "standard"
    case
      when name.include?(c)
        c
      when name.include?(d)
        d
      else
        s
    end
  end

  def self.group_available(groups)
    TicketType.where(:ticket_group => groups, :for_sale => true)
  end

  private
    def assign_default_values
      self.number_allocated = 0 if self.number_allocated.nil?
      self.size = 2 if self.size.nil?
      self.for_sale = false if self.for_sale.nil?
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:edit, :update]
  before_action :authenticate_user!

  # GET /tickets/new
  def new
    @ticket = current_user.tickets.build
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create

    @ticket = current_user.tickets.build(ticket_params)
    @ticket.status = current_user.new_ticket_status

    return render action: 'new' unless @ticket.valid?

    notice = %{You've been placed on the waiting list for your ticket.
        We will contact you via email with the result of your ticket application.}
    if @ticket.reserved?
      @ticket.charges.build([{amount: @ticket.ticket_type.price, description: @ticket.ticket_type.name},
                             {amount: @ticket.donation, description: 'Ticket donation'}])
      notice = 'Ticket successfully ordered. Please consult the Charges section.'
    end

    if @ticket.save
      if @ticket.reserved?
        UserMailer.reserved_ticket(current_user, @ticket).deliver_later
      elsif @ticket.waiting_list?
        UserMailer.waiting_list_ticket(current_user, @ticket).deliver_later
      end
      redirect_to authenticated_root_url, notice: notice
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    if @ticket.update(namechange_params)
      redirect_to authenticated_root_url, notice: 'Ticket was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = current_user.tickets.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      # params[:ticket]
      params.require(:ticket).permit(:name, :second_name, :donation, :ticket_type_id, :first_guest_date_of_birth, :second_guest_date_of_birth)
    end

    def namechange_params
      params.require(:ticket).permit(:name, :second_name, :first_guest_date_of_birth, :second_guest_date_of_birth)
    end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.haml
= simple_form_for @ticket, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean } do |f|
  = f.input :name, label: "First guest's name"
  = f.input :first_guest_date_of_birth, as: :date, label: "First guest's date of birth",
      input_html: { style: 'width: 25%; float: left;' },
      start_year: Date.today.year - 100,
      end_year: Date.today.year - 18
  = f.input :second_name, label: "Second guest's name"
  = f.input :second_guest_date_of_birth, as: :date, label: "Second guest's date of birth",
      input_html: { style: 'width: 25%; float: left;' },
      start_year: Date.today.year - 100,
      end_year: Date.today.year - 18
  - if new
    = f.association :ticket_type, collection: current_user.available_ticket_groups, as: :radio_buttons,
        label_method: lambda { |item| "#{item.name} – #{item.sold_out ? 'SOLD OUT' : number_to_currency(item.price, unit: '£')}" }
    = f.input :donation, as: :currency, label: 'Charitable Donation', input_html: { value: '5' }
    .col-sm-3
    %p.col-sm-9 The Peterhouse May Ball 2015 will be supporting Médecins Sans Frontières, chosen by current Peterhouse students.
  = f.button :submit, new ? 'Apply for ticket' : 'Change name', :class => 'btn-primary'
  = link_to 'Cancel', home_path, :class => 'btn btn-default'

app/views/tickets/_ticket_row.html.haml
%tr
  %td= ticket.name
  %td= ticket.second_name
  %td= ticket.ticket_type.short_name.to_s.humanize
  %td= ticket.status.humanize
  %td= number_to_currency(ticket.donation, unit: '£')
  %td= ticket.created_at.to_date.to_s(:long_ordinal)
  -#%td
  -#  = link_to 'Change name', edit_ticket_path(ticket), :class => 'btn btn-primary btn-xs'

app/views/tickets/_ticket_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th.col-md-2 First guest
      %th.col-md-2 Second guest
      %th.col-md-2= Ticket.human_attribute_name(:ticket_type)
      %th.col-md-2= Ticket.human_attribute_name(:status)
      %th.col-md-2= Ticket.human_attribute_name(:donation)
      %th.col-md-2= Ticket.human_attribute_name(:created_at)
      -#%th
  %tbody
    = render partial: 'tickets/ticket_row', collection: tickets, as: :ticket

app/views/tickets/edit.html.haml
.page-header
  %h1 Change name on ticket
- if @ticket.nil?
  %p Ticket not found.
  = link_to 'Back', home_path, :class => 'btn btn-default'
- else
  = render :partial => 'form', :locals => { :new => false }

app/views/tickets/new.html.haml
.page-header
  %h1 Apply for Ticket
= render :partial => 'form', :locals => { :new => true }