config/routes.rb
MayBall::Application.routes.draw do
  get 'metrics/cashflow'

  get 'metrics/payments'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root 'users#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'home', to: 'users#home'

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Peterhouse May Ball Ticketing"
    = csrf_meta_tags    
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag    "application",
        media: "all", 
        "data-turbolinks-track" => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', 
        :rel => 'apple-touch-icon-precomposed',
        :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png',
        :rel => 'apple-touch-icon-precomposed',
        :type => 'image/png', 
        :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', 
        :rel => 'apple-touch-icon-precomposed',
        :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png',
        :rel => 'apple-touch-icon-precomposed',
        :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", "data-turbolinks-track" => true
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Peterhouse May Ball 2015 Ticketing System', :authenticated_root, :class => "navbar-brand"
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li 
                %p.navbar-text Currently logged in as #{current_user.email}
              %li= link_to "Admin", rails_admin_path if current_user.admin?
              %li= link_to "Logout", destroy_user_session_path, :method => :delete
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
      %hr
        %p &copy; Peterhouse May Ball 2015

app/views/layouts/devise.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Peterhouse May Ball Ticketing"
    = csrf_meta_tags    
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag    "application",
        media: "all", 
        "data-turbolinks-track" => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", "data-turbolinks-track" => true
  %body
    .container
      .row
        .col-lg-3
        .col-lg-6
          = yield
        .col-lg-3